### ISSUE TITLE
[Napari HUB cli] Metadata enhancement

### ISSUE THREAD

**Issue by seankmartin** [Chris-N-K/napari-time_series_plotter#24]
Hi again,

I'm Sean, and I created this issue to complement #23.

While scanning your repository, I identified some metadata that are either missing, or misplaced in files that are considered as secondary or deprecated sources.

Since metadata sometimes is hard to fix automatically I created a list of what improvements you might want to look into to improve the overall quality of your [napari hub](https://napari-hub.org) listing:

* 'Screenshot/Video' entry was not found (scanned files: `.napari\DESCRIPTION.md`, `README.md`, `pyproject.toml`)
* 'Intro Paragraph' entry was not found (scanned files: `.napari\DESCRIPTION.md`, `README.md`, `pyproject.toml`)

* Usage Overview was found in `README.md`, but it is preferred to place this information in `.napari\DESCRIPTION.md`
* Installation was found in `README.md`, but it is preferred to place this information in `.napari\DESCRIPTION.md`

If you need, here are [more details about metadata and their locations](https://github.com/chanzuckerberg/napari-hub/wiki/Customizing-your-plugin%27s-listing).

As I mentioned in my PR, if some metadata is already present and I overlooked it, please feel free to contact me or [neuromusic](https://github.com/neuromusic) to tell us what could be improved!

Thank you for your help and feedback,

The napari hub and MetaCell teams.

**Comment by seankmartin** [comment]
Hi @Chris-N-K!

All sorted on our end now, thanks. You do not need to keep the same information in both the README and DESCRIPTION.

Writing a DESCRIPTION file allows you to make a napari hub specific version of your plugin information.
If you want to make a DESCRIPTION file for that purpose, then cool, otherwise you can leave the information in the README and the hub will render it as before

Cheers! Sean

**Comment by Chris-N-K** [comment]
Thanks for the reply, sounds good :)
